name: Bump release version
on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.ref }}

      - name: Get next tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 0.1.0
          DEFAULT_BUMP: minor
          TAG_CONTEXT: ${{ contains( github.ref, 'release') && 'branch' || 'repo' }}
          PRERELEASE: ${{ contains( github.ref, 'release') && true || false }}
          PRERELEASE_SUFFIX: p
          DRY_RUN: true

      - name: Update version
        shell: bash
        run: echo ${{ steps.tag.outputs.new_tag }} > version

      - name: Generate CI token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_APP_SECRET }}
          permission-contents: write

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure GH Bot User
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'


      - name: Push Tag
        run: |
          git add .
          git commit -m "[skip ci] version update"
          git push origin

          git tag ${{ steps.tag.outputs.new_tag }}
          git push origin ${{ steps.tag.outputs.new_tag }}
