name: Bump release version
on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.ref }}

      - name: Get next tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 0.1.0
          DEFAULT_BUMP: minor
          TAG_CONTEXT: ${{ contains( github.ref, 'release') && 'branch' || 'repo' }}
          PRERELEASE: ${{ contains( github.ref, 'release') && true || false }}
          PRERELEASE_SUFFIX: p
          DRY_RUN: true

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_APP_SECRET }}

      - name: Tag
        with:
          token: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[skip ci] version update"
          git push origin
          
          git tag ${{ steps.tag.outputs.new_tag }}
          git push origin ${{ steps.tag.outputs.new_tag }}
